// SPDX-License-Identifier: GPL-3.0-or-later
// HyperChess Core — hyperchess-wasm
// File: crates/hyperchess-wasm/src/geometry.rs
// Version: 1.0.0
// Copyright (c) 2026 HyperChess Developer Team

//! Procedural low-poly primitive mesh generation, used to build the placeholder
//! piece models under `src/assets/pieces/*.obj` (see `bin/gen_assets.rs`).
//!
//! Meshes are faceted (each triangle owns its own vertices/normal, no shared-vertex
//! smoothing) — that reads as a deliberate low-poly placeholder look rather than a
//! rendering bug, and keeps OBJ export trivial (no normal-averaging to get right).
//! Real piece models the user drops in later replace these files directly; nothing
//! else needs to change since the loader (`src/obj.rs`) only understands OBJ.

use glam::{Mat4, Vec3};

/// A faceted triangle mesh in the crate's own minimal form.
///
/// `positions` and `normals` are index-parallel: entry *i* of one always
/// belongs to entry *i* of the other. Because meshes here are faceted, a vertex
/// shared geometrically between two faces still appears twice, once per face,
/// each copy carrying its own face normal.
#[derive(Clone, Debug, Default)]
pub struct Mesh {
    /// One entry per vertex, in object space.
    pub positions: Vec<[f32; 3]>,
    /// Face normal, duplicated per vertex — see the note on [`Mesh`].
    pub normals: Vec<[f32; 3]>,
    /// Triangle list, 3 indices per face, indexing into `positions`/`normals` in lockstep.
    pub indices: Vec<u32>,
}

impl Mesh {
    /// Append one triangle with a normal derived from its own winding.
    ///
    /// `normalize_or_zero` rather than `normalize` so a degenerate (zero-area)
    /// triangle yields a zero normal instead of NaNs propagating into the
    /// exported OBJ.
    fn push_tri(&mut self, a: Vec3, b: Vec3, c: Vec3) {
        let n = (b - a).cross(c - a).normalize_or_zero();
        let base = self.positions.len() as u32;
        for p in [a, b, c] {
            self.positions.push(p.to_array());
            self.normals.push(n.to_array());
        }
        self.indices.extend([base, base + 1, base + 2]);
    }

    /// Append a planar quad as two triangles sharing the `a`–`c` diagonal.
    fn push_quad(&mut self, a: Vec3, b: Vec3, c: Vec3, d: Vec3) {
        // a,b,c,d in winding order around the quad.
        self.push_tri(a, b, c);
        self.push_tri(a, c, d);
    }

    /// Return a copy with `m` applied to positions.
    ///
    /// Normals go through the inverse-transpose instead of `m` itself, which is
    /// what keeps them perpendicular to the surface under non-uniform scaling —
    /// applying `m` directly would visibly skew the shading on any squashed
    /// piece part.
    pub fn transformed(&self, m: Mat4) -> Mesh {
        let normal_mat = m.inverse().transpose();
        Mesh {
            positions: self
                .positions
                .iter()
                .map(|p| m.transform_point3(Vec3::from(*p)).to_array())
                .collect(),
            normals: self
                .normals
                .iter()
                .map(|n| {
                    normal_mat
                        .transform_vector3(Vec3::from(*n))
                        .normalize_or_zero()
                        .to_array()
                })
                .collect(),
            indices: self.indices.clone(),
        }
    }

    /// Concatenate meshes into one, rebasing each part's indices onto the
    /// growing vertex buffer. This is how a piece is assembled from primitives.
    pub fn merge(parts: impl IntoIterator<Item = Mesh>) -> Mesh {
        let mut out = Mesh::default();
        for part in parts {
            let base = out.positions.len() as u32;
            out.positions.extend(part.positions);
            out.normals.extend(part.normals);
            out.indices.extend(part.indices.iter().map(|i| i + base));
        }
        out
    }

    /// Serialise to Wavefront OBJ text (`v`/`vn`/`f` only, no material data).
    pub fn to_obj(&self) -> String {
        let mut s = String::new();
        s.push_str(
            "# generated by hyperchess_3d/src/bin/gen_assets.rs — placeholder primitive piece\n",
        );
        for p in &self.positions {
            s.push_str(&format!("v {:.5} {:.5} {:.5}\n", p[0], p[1], p[2]));
        }
        for n in &self.normals {
            s.push_str(&format!("vn {:.5} {:.5} {:.5}\n", n[0], n[1], n[2]));
        }
        for tri in self.indices.chunks(3) {
            // OBJ indices are 1-based; positions/normals are index-parallel per vertex.
            s.push_str(&format!(
                "f {0}//{0} {1}//{1} {2}//{2}\n",
                tri[0] + 1,
                tri[1] + 1,
                tri[2] + 1
            ));
        }
        s
    }
}

/// Axis-aligned box centered at `center`, given full extents.
pub fn cuboid(center: Vec3, size: Vec3) -> Mesh {
    let h = size * 0.5;
    let corners = |sx: f32, sy: f32, sz: f32| center + Vec3::new(sx * h.x, sy * h.y, sz * h.z);
    let mut m = Mesh::default();
    // +Y top, -Y bottom, +X, -X, +Z, -Z — each as a quad wound CCW when viewed from outside.
    m.push_quad(
        corners(-1., 1., -1.),
        corners(-1., 1., 1.),
        corners(1., 1., 1.),
        corners(1., 1., -1.),
    );
    m.push_quad(
        corners(-1., -1., 1.),
        corners(-1., -1., -1.),
        corners(1., -1., -1.),
        corners(1., -1., 1.),
    );
    m.push_quad(
        corners(1., -1., -1.),
        corners(1., 1., -1.),
        corners(1., 1., 1.),
        corners(1., -1., 1.),
    );
    m.push_quad(
        corners(-1., -1., 1.),
        corners(-1., 1., 1.),
        corners(-1., 1., -1.),
        corners(-1., -1., -1.),
    );
    m.push_quad(
        corners(-1., -1., -1.),
        corners(-1., 1., -1.),
        corners(1., 1., -1.),
        corners(1., -1., -1.),
    );
    m.push_quad(
        corners(1., -1., 1.),
        corners(1., 1., 1.),
        corners(-1., 1., 1.),
        corners(-1., -1., 1.),
    );
    m
}

/// A truncated cone (cylinder when `radius_top == radius_bottom`, cone when `radius_top == 0`),
/// base centered at `(center.x, center.y, center.z)`, extending up by `height`.
pub fn frustum(
    center: Vec3,
    radius_bottom: f32,
    radius_top: f32,
    height: f32,
    segments: u32,
) -> Mesh {
    let mut m = Mesh::default();
    let ring = |r: f32, y: f32| -> Vec<Vec3> {
        (0..segments)
            .map(|i| {
                let a = i as f32 / segments as f32 * std::f32::consts::TAU;
                center + Vec3::new(a.cos() * r, y, a.sin() * r)
            })
            .collect()
    };
    let bottom = ring(radius_bottom, 0.0);
    let top = ring(radius_top, height);

    for i in 0..segments as usize {
        let j = (i + 1) % segments as usize;
        if radius_bottom > 0.0 {
            m.push_tri(center, bottom[j], bottom[i]);
        }
        if radius_top > 0.0 {
            let top_center = center + Vec3::new(0.0, height, 0.0);
            m.push_tri(top_center, top[i], top[j]);
        }
        // Side quad (skip degenerate when both radii are 0, which never happens for real pieces).
        m.push_quad(bottom[i], top[i], top[j], bottom[j]);
    }
    m
}

/// Closed cylinder — a [`frustum`] with equal radii.
pub fn cylinder(center: Vec3, radius: f32, height: f32, segments: u32) -> Mesh {
    frustum(center, radius, radius, height, segments)
}

/// Closed cone — a [`frustum`] whose top radius is zero, so the top cap is
/// skipped and the sides converge to the apex.
pub fn cone(center: Vec3, radius: f32, height: f32, segments: u32) -> Mesh {
    frustum(center, radius, 0.0, height, segments)
}

/// Faceted UV-sphere centered at `center`.
pub fn uv_sphere(center: Vec3, radius: f32, rings: u32, segments: u32) -> Mesh {
    let mut m = Mesh::default();
    let pt = |ring: u32, seg: u32| -> Vec3 {
        let phi = ring as f32 / rings as f32 * std::f32::consts::PI;
        let theta = seg as f32 / segments as f32 * std::f32::consts::TAU;
        center
            + Vec3::new(
                phi.sin() * theta.cos() * radius,
                phi.cos() * radius,
                phi.sin() * theta.sin() * radius,
            )
    };
    for ring in 0..rings {
        for seg in 0..segments {
            let a = pt(ring, seg);
            let b = pt(ring + 1, seg);
            let c = pt(ring + 1, (seg + 1) % segments);
            let d = pt(ring, (seg + 1) % segments);
            if ring == 0 {
                m.push_tri(a, b, c);
            } else if ring + 1 == rings {
                m.push_tri(a, b, d);
            } else {
                m.push_quad(a, b, c, d);
            }
        }
    }
    m
}

/// Torus centered at `center`, ring lying in the XZ plane.
pub fn torus(
    center: Vec3,
    major_radius: f32,
    minor_radius: f32,
    major_segs: u32,
    minor_segs: u32,
) -> Mesh {
    let mut m = Mesh::default();
    let pt = |i: u32, j: u32| -> Vec3 {
        let a = i as f32 / major_segs as f32 * std::f32::consts::TAU;
        let b = j as f32 / minor_segs as f32 * std::f32::consts::TAU;
        let ring_center = Vec3::new(a.cos() * major_radius, 0.0, a.sin() * major_radius);
        let out = Vec3::new(a.cos(), 0.0, a.sin());
        center
            + ring_center
            + out * (b.cos() * minor_radius)
            + Vec3::new(0.0, b.sin() * minor_radius, 0.0)
    };
    for i in 0..major_segs {
        for j in 0..minor_segs {
            let a = pt(i, j);
            let b = pt(i + 1, j);
            let c = pt(i + 1, (j + 1) % minor_segs);
            let d = pt(i, (j + 1) % minor_segs);
            m.push_quad(a, b, c, d);
        }
    }
    m
}
