//! The actual HyperChess 3D scene: board tiles, piece instances, highlight
//! markers, camera, and the frame render. Built on top of the bare wgpu context
//! in `gpu.rs`. Coordinate convention matches the 2D canvas renderer
//! (`board.js`) exactly so flipping the board reads the same in both modes —
//! see `square_world_xz`.

use crate::camera::Camera;
use crate::geometry::{cuboid, Mesh};
use crate::gpu::GpuContext;
use crate::obj;
use glam::{Mat4, Vec3};
use web_sys::HtmlCanvasElement;
use wgpu::util::DeviceExt;

const TILE_SIZE: f32 = 0.96;
const TILE_HEIGHT: f32 = 0.06;
const TILE_TOP_Y: f32 = TILE_HEIGHT / 2.0;
const MARKER_FULL_SIZE: f32 = 0.90;
const MARKER_DOT_SIZE: f32 = 0.32;

const LIGHT_SQ: [f32; 4] = [0.82, 0.71, 0.55, 1.0];
const DARK_SQ: [f32; 4] = [0.42, 0.29, 0.20, 1.0];
const WHITE_PIECE: [f32; 4] = [0.93, 0.91, 0.84, 1.0];
const BLACK_PIECE: [f32; 4] = [0.13, 0.12, 0.15, 1.0];
const SEL_COLOR: [f32; 4] = [1.0, 0.84, 0.2, 0.55];
const LEGAL_COLOR: [f32; 4] = [0.25, 0.85, 0.35, 0.85];
const LASTMOVE_COLOR: [f32; 4] = [0.35, 0.65, 0.95, 0.42];
const CHECK_COLOR: [f32; 4] = [0.95, 0.15, 0.15, 0.55];
const LIGHT_DIR: [f32; 4] = [-0.35, -0.85, -0.25, 0.0];

/// World-space (x, z) center of a square, matching board.js's `_sqToCanvas`
/// file/rank flip so a flipped 3D board reads identically to the flipped 2D one.
pub fn square_world_xz(sq: u8, flipped: bool) -> (f32, f32) {
    let file = (sq % 12) as i32;
    let rank = (sq / 12) as i32;
    let draw_file = if flipped { 11 - file } else { file };
    let draw_rank = if flipped { rank } else { 11 - rank };
    (draw_file as f32 + 0.5, draw_rank as f32 + 0.5)
}

/// Inverse of `square_world_xz`: world (x, z) -> square index, or `None` if
/// outside the 12x12 board.
fn world_xz_to_square(x: f32, z: f32, flipped: bool) -> Option<u8> {
    let draw_file = x.floor() as i32;
    let draw_rank = z.floor() as i32;
    if !(0..12).contains(&draw_file) || !(0..12).contains(&draw_rank) {
        return None;
    }
    let file = if flipped { 11 - draw_file } else { draw_file };
    let rank = if flipped { draw_rank } else { 11 - draw_rank };
    Some((rank * 12 + file) as u8)
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct Vertex {
    position: [f32; 3],
    normal: [f32; 3],
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct Instance {
    model: [[f32; 4]; 4],
    color: [f32; 4],
}

impl Instance {
    fn new(model: Mat4, color: [f32; 4]) -> Self {
        Self {
            model: model.to_cols_array_2d(),
            color,
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, bytemuck::Pod, bytemuck::Zeroable)]
struct CameraUniform {
    view_proj: [[f32; 4]; 4],
    light_dir: [f32; 4],
}

struct GpuMesh {
    vbuf: wgpu::Buffer,
    ibuf: wgpu::Buffer,
    count: u32,
}

fn upload_mesh(device: &wgpu::Device, mesh: &Mesh) -> GpuMesh {
    let verts: Vec<Vertex> = mesh
        .positions
        .iter()
        .zip(&mesh.normals)
        .map(|(p, n)| Vertex {
            position: *p,
            normal: *n,
        })
        .collect();
    let vbuf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: Some("mesh-vbuf"),
        contents: bytemuck::cast_slice(&verts),
        usage: wgpu::BufferUsages::VERTEX,
    });
    let ibuf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: Some("mesh-ibuf"),
        contents: bytemuck::cast_slice(&mesh.indices),
        usage: wgpu::BufferUsages::INDEX,
    });
    GpuMesh {
        vbuf,
        ibuf,
        count: mesh.indices.len() as u32,
    }
}

fn instance_buffer(device: &wgpu::Device, instances: &[Instance]) -> Option<wgpu::Buffer> {
    if instances.is_empty() {
        return None;
    }
    Some(
        device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("instance-buf"),
            contents: bytemuck::cast_slice(instances),
            usage: wgpu::BufferUsages::VERTEX,
        }),
    )
}

// Placeholder primitive meshes, generated by `bin/gen_assets.rs` into
// `src/assets/pieces/*.obj`. Order matches `pieces::PIECE_NAMES` exactly — that
// order is the encoding contract with board3d.js's board-state byte array.
// Replacing a file here with a real modeled OBJ of the same name is a drop-in
// swap; nothing else needs to change.
const PIECE_OBJ: [&str; 8] = [
    include_str!("../assets/pieces/pawn.obj"),
    include_str!("../assets/pieces/knight.obj"),
    include_str!("../assets/pieces/bishop.obj"),
    include_str!("../assets/pieces/rook.obj"),
    include_str!("../assets/pieces/queen.obj"),
    include_str!("../assets/pieces/king.obj"),
    include_str!("../assets/pieces/eagle.obj"),
    include_str!("../assets/pieces/hawk.obj"),
];

fn create_depth_view(
    device: &wgpu::Device,
    config: &wgpu::SurfaceConfiguration,
) -> (wgpu::TextureView, wgpu::TextureFormat) {
    let format = wgpu::TextureFormat::Depth32Float;
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("depth"),
        size: wgpu::Extent3d {
            width: config.width.max(1),
            height: config.height.max(1),
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    });
    (
        tex.create_view(&wgpu::TextureViewDescriptor::default()),
        format,
    )
}

pub struct Scene {
    ctx: GpuContext,
    pipeline: wgpu::RenderPipeline,
    depth_view: wgpu::TextureView,
    camera_buf: wgpu::Buffer,
    bind_group: wgpu::BindGroup,
    pub camera: Camera,

    tile_mesh: GpuMesh,
    marker_full_mesh: GpuMesh,
    marker_dot_mesh: GpuMesh,
    piece_meshes: [GpuMesh; 8],

    /// 0 = empty; else `(color << 4) | kind`, kind 1..=8 indexing `pieces::PIECE_NAMES`.
    board: [u8; 144],
    flipped: bool,
    selected: Option<u8>,
    legal: Vec<u8>,
    last_move: Option<(u8, u8)>,
    checked_king: Option<u8>,
    anim: Option<MoveAnim>,
}

/// An in-flight move animation: the moving piece glides `from` -> `to` (with a
/// small vertical hop) while a captured piece, if any, shrinks and fades out in
/// place. `piece_byte`/`captured` are snapshotted from the board *before* the
/// move is applied, since `Scene::set_board` overwrites it with the post-move
/// state immediately after `animate_move` is called.
struct MoveAnim {
    from: u8,
    to: u8,
    piece_byte: u8,
    captured: Option<(u8, u8)>,
    start_ms: f64,
    duration_ms: f64,
}

const ANIM_DURATION_MS: f64 = 300.0;
const ANIM_HOP_HEIGHT: f32 = 0.18;

fn now_ms() -> f64 {
    web_sys::window()
        .and_then(|w| w.performance())
        .map(|p| p.now())
        .unwrap_or(0.0)
}

fn ease_out_cubic(t: f32) -> f32 {
    1.0 - (1.0 - t).powi(3)
}

impl Scene {
    pub async fn new(canvas: HtmlCanvasElement) -> Result<Self, String> {
        let ctx = GpuContext::new(canvas).await?;
        let device = &ctx.device;

        let (depth_view, depth_format) = create_depth_view(device, &ctx.config);

        let camera_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("camera-uniform"),
            size: std::mem::size_of::<CameraUniform>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("camera-bgl"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            }],
        });
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("camera-bg"),
            layout: &bind_group_layout,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: camera_buf.as_entire_binding(),
            }],
        });

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("scene-shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("shaders/scene.wgsl").into()),
        });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("scene-pipeline-layout"),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });

        let vertex_layout = wgpu::VertexBufferLayout {
            array_stride: std::mem::size_of::<Vertex>() as wgpu::BufferAddress,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &[
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x3,
                    offset: 0,
                    shader_location: 0,
                },
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x3,
                    offset: 12,
                    shader_location: 1,
                },
            ],
        };
        let instance_layout = wgpu::VertexBufferLayout {
            array_stride: std::mem::size_of::<Instance>() as wgpu::BufferAddress,
            step_mode: wgpu::VertexStepMode::Instance,
            attributes: &[
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x4,
                    offset: 0,
                    shader_location: 2,
                },
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x4,
                    offset: 16,
                    shader_location: 3,
                },
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x4,
                    offset: 32,
                    shader_location: 4,
                },
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x4,
                    offset: 48,
                    shader_location: 5,
                },
                wgpu::VertexAttribute {
                    format: wgpu::VertexFormat::Float32x4,
                    offset: 64,
                    shader_location: 6,
                },
            ],
        };

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("scene-pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                buffers: &[Some(vertex_layout), Some(instance_layout)],
                compilation_options: Default::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: ctx.config.format,
                    blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: Default::default(),
            }),
            primitive: wgpu::PrimitiveState {
                cull_mode: None,
                ..Default::default()
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: depth_format,
                depth_write_enabled: Some(true),
                depth_compare: Some(wgpu::CompareFunction::Less),
                stencil: wgpu::StencilState::default(),
                bias: wgpu::DepthBiasState::default(),
            }),
            multisample: wgpu::MultisampleState::default(),
            multiview_mask: None,
            cache: None,
        });

        let tile_mesh = upload_mesh(
            device,
            &cuboid(Vec3::ZERO, Vec3::new(TILE_SIZE, TILE_HEIGHT, TILE_SIZE)),
        );
        // Markers sit just above the tile's top surface (TILE_TOP_Y), not centered
        // on it, or they'd render fully inside the opaque tile volume and vanish.
        let marker_full_mesh = upload_mesh(
            device,
            &cuboid(
                Vec3::new(0.0, TILE_TOP_Y + 0.01, 0.0),
                Vec3::new(MARKER_FULL_SIZE, 0.02, MARKER_FULL_SIZE),
            ),
        );
        let marker_dot_mesh = upload_mesh(
            device,
            &cuboid(
                Vec3::new(0.0, TILE_TOP_Y + 0.02, 0.0),
                Vec3::new(MARKER_DOT_SIZE, 0.02, MARKER_DOT_SIZE),
            ),
        );

        let piece_meshes: Vec<GpuMesh> = PIECE_OBJ
            .iter()
            .map(|src| upload_mesh(device, &obj::parse(src)))
            .collect();
        let piece_meshes: [GpuMesh; 8] = piece_meshes
            .try_into()
            .unwrap_or_else(|_| unreachable!("PIECE_OBJ has exactly 8 entries"));

        Ok(Self {
            ctx,
            pipeline,
            depth_view,
            camera_buf,
            bind_group,
            camera: Camera::default(),
            tile_mesh,
            marker_full_mesh,
            marker_dot_mesh,
            piece_meshes,
            board: [0u8; 144],
            flipped: false,
            selected: None,
            legal: Vec::new(),
            last_move: None,
            checked_king: None,
            anim: None,
        })
    }

    pub fn resize(&mut self, width: u32, height: u32) {
        self.ctx.resize(width, height);
        let (view, _) = create_depth_view(&self.ctx.device, &self.ctx.config);
        self.depth_view = view;
    }

    pub fn orbit(&mut self, dyaw: f32, dpitch: f32) {
        self.camera.orbit(dyaw, dpitch);
    }

    pub fn zoom(&mut self, factor: f32) {
        self.camera.zoom(factor);
    }

    pub fn set_board(&mut self, board: &[u8], flipped: bool) {
        let n = board.len().min(144);
        self.board[..n].copy_from_slice(&board[..n]);
        self.board[n..].fill(0);
        self.flipped = flipped;
    }

    /// Snapshots the piece currently on `from` (and any enemy piece on `to`, as a
    /// capture) and starts a glide animation. Call this *before* `set_board` lands
    /// the post-move position, since it reads the pre-move board to know what to
    /// animate; `set_board` right after is what makes the destination "true" once
    /// the animation finishes.
    pub fn animate_move(&mut self, from: u8, to: u8) {
        let piece_byte = self.board.get(from as usize).copied().unwrap_or(0);
        if piece_byte == 0 {
            self.anim = None;
            return;
        }
        let captured_byte = self.board.get(to as usize).copied().unwrap_or(0);
        let captured = (captured_byte != 0).then_some((captured_byte, to));
        self.anim = Some(MoveAnim {
            from,
            to,
            piece_byte,
            captured,
            start_ms: now_ms(),
            duration_ms: ANIM_DURATION_MS,
        });
    }

    /// Whether a move animation is still in flight — JS uses this to decide
    /// whether to keep pumping the render loop for a smooth glide.
    pub fn is_animating(&self) -> bool {
        self.anim.is_some()
    }

    pub fn set_selection(
        &mut self,
        selected: Option<u8>,
        legal: Vec<u8>,
        last_move: Option<(u8, u8)>,
        checked_king: Option<u8>,
    ) {
        self.selected = selected;
        self.legal = legal;
        self.last_move = last_move;
        self.checked_king = checked_king;
    }

    /// Canvas-space pixel coordinates -> board square index, via ray/plane
    /// intersection through the current (possibly orbited) camera.
    pub fn pick(&self, x: f32, y: f32) -> Option<u8> {
        let w = self.ctx.config.width as f32;
        let h = self.ctx.config.height as f32;
        if w <= 0.0 || h <= 0.0 {
            return None;
        }
        let ndc_x = (x / w) * 2.0 - 1.0;
        let ndc_y = 1.0 - (y / h) * 2.0;
        let hit = self.camera.plane_hit(ndc_x, ndc_y, self.ctx.aspect())?;
        world_xz_to_square(hit.x, hit.z, self.flipped)
    }

    pub fn render(&mut self) {
        let frame = match self.ctx.surface.get_current_texture() {
            wgpu::CurrentSurfaceTexture::Success(f) => f,
            wgpu::CurrentSurfaceTexture::Suboptimal(f) => f,
            _ => {
                self.ctx
                    .surface
                    .configure(&self.ctx.device, &self.ctx.config);
                return;
            }
        };
        let view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let camera_uniform = CameraUniform {
            view_proj: self.camera.view_proj(self.ctx.aspect()).to_cols_array_2d(),
            light_dir: LIGHT_DIR,
        };
        self.ctx
            .queue
            .write_buffer(&self.camera_buf, 0, bytemuck::bytes_of(&camera_uniform));

        // Tiles: full 12x12 checkerboard, rebuilt every frame (144 instances is cheap).
        let mut tiles = Vec::with_capacity(144);
        for sq in 0u8..144 {
            let (x, z) = square_world_xz(sq, self.flipped);
            let file = sq % 12;
            let rank = sq / 12;
            let color = if (file + rank) % 2 == 0 {
                DARK_SQ
            } else {
                LIGHT_SQ
            };
            tiles.push(Instance::new(
                Mat4::from_translation(Vec3::new(x, 0.0, z)),
                color,
            ));
        }

        let mut full_markers = Vec::new();
        if let Some(sq) = self.selected {
            let (x, z) = square_world_xz(sq, self.flipped);
            full_markers.push(Instance::new(
                Mat4::from_translation(Vec3::new(x, 0.0, z)),
                SEL_COLOR,
            ));
        }
        if let Some((from, to)) = self.last_move {
            for sq in [from, to] {
                let (x, z) = square_world_xz(sq, self.flipped);
                full_markers.push(Instance::new(
                    Mat4::from_translation(Vec3::new(x, 0.0, z)),
                    LASTMOVE_COLOR,
                ));
            }
        }
        if let Some(sq) = self.checked_king {
            let (x, z) = square_world_xz(sq, self.flipped);
            full_markers.push(Instance::new(
                Mat4::from_translation(Vec3::new(x, 0.0, z)),
                CHECK_COLOR,
            ));
        }
        let mut dot_markers = Vec::new();
        for &sq in &self.legal {
            let (x, z) = square_world_xz(sq, self.flipped);
            dot_markers.push(Instance::new(
                Mat4::from_translation(Vec3::new(x, 0.0, z)),
                LEGAL_COLOR,
            ));
        }

        // Resolve the in-flight move animation's progress once per frame, and
        // retire it once it completes (the destination then renders normally
        // from `self.board`, which already reflects the post-move state).
        let now = now_ms();
        let anim_t = self
            .anim
            .as_ref()
            .map(|a| (((now - a.start_ms) / a.duration_ms) as f32).clamp(0.0, 1.0));
        if anim_t == Some(1.0) {
            self.anim = None;
        }

        // Pieces, grouped per kind so each mesh gets exactly one instanced draw call.
        let mut piece_instances: [Vec<Instance>; 8] = Default::default();
        for sq in 0u8..144 {
            if let Some(a) = &self.anim {
                if sq == a.to {
                    continue; // drawn as the flying/animated instance below instead
                }
            }
            let byte = self.board[sq as usize];
            if byte == 0 {
                continue;
            }
            let kind_idx = ((byte & 0x0F).saturating_sub(1)) as usize;
            if kind_idx >= 8 {
                continue;
            }
            let is_black = (byte >> 4) & 1 == 1;
            let (x, z) = square_world_xz(sq, self.flipped);
            let color = if is_black { BLACK_PIECE } else { WHITE_PIECE };
            piece_instances[kind_idx].push(Instance::new(
                Mat4::from_translation(Vec3::new(x, TILE_TOP_Y, z)),
                color,
            ));
        }

        if let Some(a) = &self.anim {
            let t = anim_t.unwrap_or(1.0);
            let te = ease_out_cubic(t);
            let kind_idx = ((a.piece_byte & 0x0F).saturating_sub(1)) as usize;
            if kind_idx < 8 {
                let is_black = (a.piece_byte >> 4) & 1 == 1;
                let color = if is_black { BLACK_PIECE } else { WHITE_PIECE };
                let (fx, fz) = square_world_xz(a.from, self.flipped);
                let (tx, tz) = square_world_xz(a.to, self.flipped);
                let hop = (t * std::f32::consts::PI).sin() * ANIM_HOP_HEIGHT;
                let x = fx + (tx - fx) * te;
                let z = fz + (tz - fz) * te;
                piece_instances[kind_idx].push(Instance::new(
                    Mat4::from_translation(Vec3::new(x, TILE_TOP_Y + hop, z)),
                    color,
                ));
            }
            if let Some((cap_byte, cap_sq)) = a.captured {
                let cap_kind = ((cap_byte & 0x0F).saturating_sub(1)) as usize;
                if cap_kind < 8 {
                    let is_black = (cap_byte >> 4) & 1 == 1;
                    let mut color = if is_black { BLACK_PIECE } else { WHITE_PIECE };
                    color[3] *= 1.0 - te;
                    let scale = (1.0 - te * 0.85).max(0.15);
                    let (x, z) = square_world_xz(cap_sq, self.flipped);
                    let m = Mat4::from_translation(Vec3::new(x, TILE_TOP_Y, z))
                        * Mat4::from_scale(Vec3::splat(scale));
                    piece_instances[cap_kind].push(Instance::new(m, color));
                }
            }
        }

        let tiles_buf = instance_buffer(&self.ctx.device, &tiles);
        let full_buf = instance_buffer(&self.ctx.device, &full_markers);
        let dot_buf = instance_buffer(&self.ctx.device, &dot_markers);
        let piece_bufs: Vec<Option<wgpu::Buffer>> = piece_instances
            .iter()
            .map(|v| instance_buffer(&self.ctx.device, v))
            .collect();

        let mut encoder = self
            .ctx
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("frame-encoder"),
            });
        {
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("main-pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    depth_slice: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.06,
                            g: 0.07,
                            b: 0.10,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: Some(wgpu::RenderPassDepthStencilAttachment {
                    view: &self.depth_view,
                    depth_ops: Some(wgpu::Operations {
                        load: wgpu::LoadOp::Clear(1.0),
                        store: wgpu::StoreOp::Discard,
                    }),
                    stencil_ops: None,
                }),
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });
            pass.set_pipeline(&self.pipeline);
            pass.set_bind_group(0, &self.bind_group, &[]);

            let draw = |pass: &mut wgpu::RenderPass,
                        mesh: &GpuMesh,
                        buf: &Option<wgpu::Buffer>,
                        count: usize| {
                let Some(buf) = buf else { return };
                pass.set_vertex_buffer(0, mesh.vbuf.slice(..));
                pass.set_vertex_buffer(1, buf.slice(..));
                pass.set_index_buffer(mesh.ibuf.slice(..), wgpu::IndexFormat::Uint32);
                pass.draw_indexed(0..mesh.count, 0, 0..count as u32);
            };

            draw(&mut pass, &self.tile_mesh, &tiles_buf, tiles.len());
            draw(
                &mut pass,
                &self.marker_full_mesh,
                &full_buf,
                full_markers.len(),
            );
            draw(
                &mut pass,
                &self.marker_dot_mesh,
                &dot_buf,
                dot_markers.len(),
            );
            for (idx, buf) in piece_bufs.iter().enumerate() {
                draw(
                    &mut pass,
                    &self.piece_meshes[idx],
                    buf,
                    piece_instances[idx].len(),
                );
            }
        }
        self.ctx.queue.submit(std::iter::once(encoder.finish()));
        self.ctx.queue.present(frame);
    }
}
